name: Docker Build and Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: myusername/my-docker-image
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.DOCKER_IMAGE }}:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true

    - name: Check for vulnerabilities
      id: vuln_check
      run: |
        vulnerabilities=$(jq '.runs[].results[].ruleId' trivy-results.sarif | wc -l)
        echo "Vulnerabilities found: $vulnerabilities"
        echo "VULN_COUNT=$vulnerabilities" >> $GITHUB_ENV
        if [ $vulnerabilities -gt 0 ]; then
          echo "has_vulnerabilities=true" >> $GITHUB_OUTPUT
        else
          echo "has_vulnerabilities=false" >> $GITHUB_OUTPUT
        fi

    - name: Send Slack notification
      if: steps.vuln_check.outputs.has_vulnerabilities == 'true'
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Vulnerabilities found in Docker image. Count: ${{ env.VULN_COUNT }}'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}